image: humancellatlas/dss-build-box
# The Docker image `humancellatlas/dss-build-box` is created through a manual process from
# `${DSS_HOME}/allspark.Dockerfile`. See the contents of `${DSS_HOME}/allspark.Dockerfile`
# creation and usage instructions.

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DSS_ES_TIMEOUT: 30
  DSS_UNITTEST_OPTS: "-v"
  GITHUB_API: "https://api.github.com"

stages:
  - deploy
  - test

before_script:
  - date && date -u
  - export COMMITS_URL=${GITHUB_API}/repos/HumanCellAtlas/data-store/commits
  - if [[ CI_COMMIT_SHA != $(http GET $COMMITS_URL sha==$CI_COMMIT_REF_NAME | jq -r '.[0]["sha"]') ]]; then exit 1; fi
# TODO: figure out how to get the gitlab-runner to not clone the repo as root - Brian H
  - cp -r /HumanCellAtlas/data-store ~/data-store && cd ~/data-store
  - git reset --hard HEAD
  - virtualenv ~/venv
  - source ~/venv/bin/activate
  - pip install -r requirements-dev.txt
  - source environment
  - source environment.prod
  - scripts/dss-ops.py secrets get application_secrets.json > application_secrets.json
  - scripts/dss-ops.py secrets get gcp-credentials.json > gcp-credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json

deploy:
  stage: deploy
  script:
    - make plan-infra
    - make deploy
    - scripts/set_version.sh
  environment:
    name: prod
    url: https://dss.data.humancellatlas.org
  only:
    - prod
  when: manual

test:
  stage: test
  script:
    - make smoketest-prod
  dependencies:
    - deploy
  only:
    - prod
